services:
  - type: web
    name: phosur
    runtime: docker
    repo: https://github.com/harmitvagadiya123-dotcom/Phosur
    branch: main
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: NOTIFY_TO
        sync: false
      - key: NOTIFY_CC
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SHEET_NAME
        sync: false
      - key: GOOGLE_CREDENTIALS_BASE64
        sync: false
      - key: OPENROUTER_API_KEY
        value: "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"
      - key: BG001_SHEET_ID
        value: "1bnz46ES2olQP7vPqvIpthBhF08TQ5RCN28ytcjjszsM"

